### ISSUE TITLE
Working with LiPD files 

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#10]
For LiPD directory:
- mapping

For LiPD files: 
- dashboard.

Also show how to manipulate and the use of various LiPDs to LiPDSeries transforms.

**Comment by khider** [comment]
Completed in [676474a](https://github.com/LinkedEarth/PyleoTutorials/commit/676474a79211aba90cae72fce80754ce239e40c4)

**Comment by alexkjames** [comment]
Ran through this yesterday, I think I fixed a typo and that was pretty much it. looks good
