### ISSUE TITLE
SSA Tutorial

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#11]
Use SSA tutorial from Julien

**Comment by CommonClimate** [comment]
done in b79357f

**Comment by CommonClimate** [comment]
@alexkjames I modified defaults on `modeplot()` today , which you can try using the Dev version. Can you give this another go and sign off if everything is good? We're in issue-closing mode here...

**Comment by alexkjames** [comment]
Re-ran with new pyleoclim dev version, everything looked good to me, all set here.
