### ISSUE TITLE
Basic timeseries manipulation with Pyleoclim

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#13]
- Slicing
- standadizing
- gaussianize
- stats

Optional (the functions needs some TLC)
- Detecting gaps

**Comment by khider** [comment]
I added a plot showing the standardized, gaussianized, and the original series to the notebook. There is a comment about the histograms at the end from Julien.

**Comment by jordanplanders** [comment]
Pushed with revised KDE
