### ISSUE TITLE
Basic operations with MulitpleSeries/EnsembleSeries

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#14]
1. common_time
2. stackplot (including showing how to change the labels for an existing Series/MS object)
- colormap changes
- Labels (none, some, changes)
- shift factor. 

For ensembleSeries
1. Envelope/traces

**Comment by alexkjames** [comment]
Reviewed, fixed a couple typos and changed a little bit of language, looks good!
