### ISSUE TITLE
Spectral Analysis

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#15]
Show how the various methods work and the effect of parameters (e.g, c for WWZ, n50 for Lomb-Scargle, BW for MTM, windows for Welch), the frequency vector options + effect of detrending/binning.

**Comment by khider** [comment]
Done in [daf4178](https://github.com/LinkedEarth/PyleoTutorials/commit/daf4178a746f328dda70fefaea55ff3fe90b4cf6)

**Comment by CommonClimate** [comment]
Edits completed in d4c4f31b6453996d5208ec93eda5f450914c9a13
