### ISSUE TITLE
Enable CI for the notebooks

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#19]
We should be able to re-use the notebooks to run the "tests". Only thing to be careful about is that some of the notebooks require user input (i.e., choose your timeseries from a lipd file). So this particular line for the tests notebook would have to be rewritten to use the `number` parameter.

I propose to create a test folder that contain the test notebooks that are updated for no user inputs. Or we modify to not allow for user inputs. This problem should disappear once we integrate pylipd.

**Comment by CommonClimate** [comment]
@alexkjames I think you can close this now
