### ISSUE TITLE
Correlation notebook run time

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/PyleoTutorials#26]
The L2_correlations notebook is pretty heavy (minimum 37 minute run time, which really slows down CI), could be worth discussing moving to paleobooks and replacing with a more lightweight example.

**Comment by khider** [comment]
It would be very hard to come up with a smaller example that would still be interesting scientifically and showcase FDR. Maybe we just don't run this notebook through the tests and we know that we should go visit it once in a while and run manually when touching the underlying functions.

**Comment by CommonClimate** [comment]
3 options:
- use smaller geographic domain
- coarser resolution (2deg --> 5deg); still should be OPeNDAP-accessible
- use flexible multi-threading (Github actions use 2 cores in parallel)

**Comment by CommonClimate** [comment]
Better idea: emulate the GeoChronR tutorial.   Data are here:
- http://lipdverse.org/geoChronR-examples/Hulucave.Wang.2001.lpd
- http://lipdverse.org/geoChronR-examples/GISP2.Alley.2000.lpd
However, they have no age ensembles.  @alexkjames should have a lipd file of Hulu with age ensemble, and for GISP2 we can generate the ensemble using `pyleo.utils.tsmodel.random_time_axis` (random_choice option with 2% symmetric uncertainty)

**Comment by CommonClimate** [comment]
done as of #55
