### ISSUE TITLE
Creating Multiple Panels

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#3]
Create a tutorial showing how Matplotlib subplots can be used in combination with returned fig/ax from Pyleoclimn figures. An example is from the correlation figure in the Pyleoclim manuscript.

**Comment by khider** [comment]
Repeat this example: https://pyleoclim-util.readthedocs.io/en/master/core/api.html#pyleoclim.core.multipleseries.MultipleSeries.common_time

**Comment by khider** [comment]
Putting two correlation figures side-by-side:

```
fig,ax = plt.subplots(2,1,figsize=(5,8))
corr_ens.plot(ax=ax[0])
corr_Kuroshio.plot(ax=ax[1])
ax[0].set_xlim([-0.5,0.7])
ax[1].set_xlim([-0.5,0.7])
plt.subplots_adjust(hspace=0.4)
```

**Comment by CommonClimate** [comment]
completed in 1cb26d434a72af197d65417e84004cb64e27c7f5
