### ISSUE TITLE
Update PCA notebook

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/PyleoTutorials#45]
the "data wrangling" section needs to showcase the newly developed MGS time/lat plot, and the soon-to-be developed Resolution class (and plot) for MultipleSeries.

**Comment by CommonClimate** [comment]
This should be good to go now, and we can add MC-PCA in there

**Comment by alexkjames** [comment]
Addressed by #58

**Comment by alexkjames** [comment]
Addressed with #67

Once MulEnsGeoSeries.stackplot gets added, we'll want to add that to the notebook

**Comment by CommonClimate** [comment]
Addressed by #69
