### ISSUE TITLE
Interpolation vs bin vs gkernel and effect on spectral analysis

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#5]
Explore the difference between the different imputation method and effect on spectral analysis

**Comment by CommonClimate** [comment]
this was done in L2_spectral_analysis.ipynb, no? @khider I'll let you close this one

**Comment by khider** [comment]
Done with autoTS. See this repo: https://github.com/khider/OrbitalCycles. 

@CommonClimate please link in spectral notebook.

**Comment by CommonClimate** [comment]
Done in [73b9072](https://github.com/LinkedEarth/PyleoTutorials/commit/73b9072db1577772eb897c490db31f5e2575b97c). Turns out the notebook already had a rudimentary exploration of that anyway.
