### ISSUE TITLE
Pyleoclim correlation methods

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/PyleoTutorials#6]
explain the different ways significance is assessed, especially over a grid.

**Comment by CommonClimate** [comment]
remote access ERSST v5 through xarray: https://psl.noaa.gov/thredds/dodsC/Datasets/noaa.ersst.v5/sst.mnmean.nc

**Comment by khider** [comment]
Look at creating multiple panels for the figure (Pyleoclim Paper)

**Comment by CommonClimate** [comment]
- [  ] load Palmyra record from Ocn-Palmyra.Nurhati.2011.lpd
- [  ]  load ERSSTv5  data 
- [  ]  compute NINO3.4 using xarray. re-use [this](https://foundations.projectpythia.org/core/xarray/enso-xarray.html)
- [  ] compute correlations between Palmyra and NINO3.4, illustrating 3 ways to assess significance
- [  ]  compute correlations between Palmyra and grid SST, mapping areas of significance.

**Comment by CommonClimate** [comment]
completed in 58d3a9f917bb8c2cd75fc6610388e37c2369ba54
