### ISSUE TITLE
Coherence/Wavelet

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#7]
Repurpose the example from the documentation to create a tutorial on how to interpret coherence and wavelet plots.

**Comment by CommonClimate** [comment]
completed in ce99c5333781a3753b496d782deaa1bb630d4e2e. @khider please review

**Comment by khider** [comment]
Reviewed in [aec3c](https://github.com/LinkedEarth/PyleoTutorials/commit/aec3cd639de43907e3307ff45005ddb4538bd214):

* Corrected a few typos
* Added a comment about being able to load from a URL directly from Pandas
