### ISSUE TITLE
Series - How to create from various sources

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#9]
We should have several notebooks illustrating how to get a Series (or LiPD Series) object from:
1. a csv through Pandas (show how to skip lines and enter headers; the LR04 dataset needs line skipping at the beginning)
2. a LiPD file (maybe use either ODP846 or Crystal Cave). 

And show a simple plot

**Comment by CommonClimate** [comment]
3.  p2k_ngeo19_recons.nc

**Comment by CommonClimate** [comment]
resolved in ba61ad796e67a0d2e0c660f6f386c7e4092390ad
